name: Doc build

on:
  push:
    branches: [ master ]
    paths:
      - 'i18n/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'i18n/**'

jobs:
  build:
    strategy:
      matrix:
        locale: ['en', 'ko', 'de', 'es', 'fr', 'it', 'ja', 'pt', 'br', 'hi', 'id', 'ru', 'th', 'tl']

    runs-on: ubuntu-latest-8-cores

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16.14.1"
          cache: 'npm'
      - name: Cache Docusaurus artifacts
        id: cache-docusaurus
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-docusaurus
          path: |
            .docusaurus
            build
      - if: ${{ steps.cache-docusaurus.outputs.cache-hit != 'true' }}
        name: State of Docusaurus cache
        continue-on-error: true
        run: echo "Docusaurus cache miss, resulting build will be slower"
      - name: Cache node_modules
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          path: node_modules
      - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        name: State of node_modules cache
        continue-on-error: true
        run: echo "Package dependencies changed, unable to use node_modules cache"
      - run: yarn install --frozen-lockfile
      - run: yarn build --locale ${{ matrix.locale }}
