# This is a basic workflow to help you get started with Actions

name: Master deployment

on:
  push:
    branches: [master]
    paths:
      - 'i18n/**'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        locale: ['en', 'ko', 'de', 'es', 'fr', 'it', 'ja', 'pt', 'br', 'hi', 'id', 'ru', 'th', 'tl']

    runs-on: ubuntu-latest-8-cores

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: INSTALL
        run: rm -rf node_modules && yarn install --immutable --immutable-cache --check-cache

      - name: Build
        run: yarn build --locale ${{ matrix.locale }}

      - name: Uploading to s3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.POLYGON_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.POLYGON_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.POLYGON_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: ${{secrets.TARGET_DIRECTORY}}

      - name: invalidate cloudfront distribution and wait for completion
        uses: muratiger/invalidate-cloudfront-and-wait-for-completion-action@master
        env:
          DISTRIBUTION_ID: ${{ secrets.POLYGON_CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.POLYGON_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.POLYGON_AWS_SECRET_ACCESS_KEY }}
